### PR TITLE
Adds a test to check that all deployments build successfully.

### PR DESCRIPTION
**Pull request by Miles-Garnsey**
**What this PR does**:

What is says on the tin. Make sure all 6(!) of our kustomize deployments successfully build.

Doesn't need to be in 1.0, getting it into `main` later is fine.

**Which issue(s) this PR fixes**:
No issue raised.

**Checklist**
- [ ] Changes manually tested
- [ ] Automated Tests added/updated
- [ ] Documentation added/updated
- [ ] CHANGELOG.md updated (not required for documentation PRs)
- [ ] CLA Signed:  [DataStax CLA](https://cla.datastax.com/)

### CODE REVIEW

**Review by adejanovski — APPROVED** [review]

**Comment by bradfordcp** [comment]
Is this issue in the right state?

**Comment by Miles-Garnsey** [comment]
This is actually a PR instead of an issue @bradfordcp. We don't have an issue raised for it, as I put it together in a hurry just prior to the operator release. I think it is a pretty good idea to move ahead with merging it given that we've seen many issues with broken kustomize configs.

**Review by jeffbanks — APPROVED** [review]
Look reasonable to me.

**Comment by Miles-Garnsey** [comment]
Let's get this closed then. I think Alexander had approved previously, it may be my oversight that this wasn't previously merged.

**Pull request merged**
