### PR TITLE
Additional annotations

### LINKED ISSUE #1094: Add commonAnnotations to Cassandra metadata
**What is missing?**

There should be a `commonAnnotations` field in the [cassandra.metadata](https://docs.k8ssandra.io/reference/crd/k8ssandra-operator-crds-latest/#k8ssandraclusterspeccassandrametadata) section of the ressource `K8ssandraCluster`. 

**Why do we need it?**

Other operators in our Kubernetes cluster are interfering with the resources created by the cass-operator, and we need to add annotations to exclude these resources from the other operators.

**Environment**

* K8ssandra Operator version:

    `v1.9.1`
    
    

**Anything else we need to know?**:
No.

### PR DESCRIPTION
**Pull request by Miles-Garnsey**
**What this PR does**:

Exposes cass-operator's new AdditionalAnnotations field in the CRD.

**Which issue(s) this PR fixes**:
Fixes #1094 

**Checklist**
- [ ] Changes manually tested
- [ ] Automated Tests added/updated
- [ ] Documentation added/updated
- [ ] CHANGELOG.md updated (not required for documentation PRs)
- [ ] CLA Signed:  [DataStax CLA](https://cla.datastax.com/)

### CODE REVIEW

**Comment by Miles-Garnsey** [comment]
This should be good to go... There is one failing test but I don't think it is related - probably a flake but I'm re-running.

**Comment by Miles-Garnsey** [comment]
Alex says: 

1. We need to add something like [this](https://github.com/Miles-Garnsey/k8ssandra-operator/commit/d6964bc9c786400c6403abddac3da533967827e1#diff-c20100b9e8c5c41aeb5a8334a20d2947e788ee5c87a835dba2295bc3ca854202R10-R14) so that we deploy the right cass-operator with the new fields.
2. He wants an e2e test for the new field as well.

**Comment by Miles-Garnsey** [comment]
Looks like we can't progress this as we don't have a cass-operator image right now due to CI failures. I don't know how to fix those so will put this on hold pending a new image being built.

**Review by adejanovski — APPROVED** [review]
Works great!

Approved, pending passing unit tests (I think it's just a flake and just re-ran them).

**Comment by Miles-Garnsey** [comment]
Manually tested one more time, but this looks good to go indeed.

**Pull request merged**
