### PR TITLE
rename property cassandraTelemetry property [K8SSAND-1252]

### LINKED ISSUE #411: K8SSAND-1252 ⁃ Rename cassandraTelemetry property to just telemetry
**What is missing?**
The `casandra` part of the `cassandraTelemetry` property name is redundant and unnecessary.

Here is an example manifest:

```yaml
apiVersion: k8ssandra.io/v1alpha1
kind: K8ssandraCluster
metadata:
  name: test
  namespace: k8ssandra-operator
spec:
  cassandra:
    datacenters:
    - config:
        jvmOptions:
          heapSize: 384Mi
      metadata:
        name: dc1
      size: 1
      storageConfig:
        cassandraDataVolumeClaimSpec:
          accessModes:
          - ReadWriteOnce
          resources:
            requests:
              storage: 5Gi
          storageClassName: standard
    serverVersion: 3.11.11
    cassandraTelemetry:
      prometheus:
        enabled: true
  stargate:
    allowStargateOnDataNodes: true
    size: 1
    telemetry:
      prometheus:
        enabled: true
```

**Why do we need it?**
Changing the name to just `telemetry` removes the redundancy and makes the naming consistent with the stargate property. It is already clear that the property corresponds to Cassandra as it is a child property under the `cassandra` property.

**Environment**

* K8ssandra Operator version:

    `v0.5.0`

┆Issue is synchronized with this [Jira Task](https://k8ssandra.atlassian.net/browse/K8SSAND-1252) by [Unito](https://www.unito.io)
┆fixVersions: k8ssandra-operator-v1.0.0
┆friendlyId: K8SSAND-1252
┆priority: Medium

### PR DESCRIPTION
**Pull request by jsanda**
**What this PR does**:
Renames the property to just `telemetry`

**Which issue(s) this PR fixes**:
Fixes #411 

**Checklist**
- [ ] Changes manually tested
- [ ] Automated Tests added/updated
- [ ] Documentation added/updated
- [x] CHANGELOG.md updated (not required for documentation PRs)
- [x] CLA Signed:  [DataStax CLA](https://cla.datastax.com/)

### CODE REVIEW

**Review by adutra — APPROVED** [review]

**Comment by Miles-Garnsey** [comment]
Why are we doing this? We have previously discussed it and concluded that it is a bad idea given that Stargate and Reaper properties are also held within the `cassandra` field. 

Has that rationale changed since we had this discussion?

**Review by Miles-Garnsey — CHANGES_REQUESTED** [review]
Why are we doing this? We have previously discussed it and concluded that it is a bad idea given that Stargate and Reaper properties are also held within the cassandra field.

Has that rationale changed since we had this discussion?

**Comment by jsanda** [comment]
I think it  is clear from the parent/child relationships or nesting of properties that `cassandraTelemetry` or `telemetry` applies to Cassandra. Other than the `CassandraConfig` property, we don't prefix any of the other property names with `cassandra`.

@jdonenine thoughts?

**Comment by Miles-Garnsey** [comment]
> I think it is clear from the parent/child relationships or nesting of properties that cassandraTelemetry or telemetry applies to Cassandra. Other than the CassandraConfig property, we don't prefix any of the other property names with cassandra.

Given that other fields of the parent include `Stargate`, I disagree in this case...

**Comment by jsanda** [comment]
A trimmed down example for comparison.

before:

```yaml
apiVersion: k8ssandra.io/v1alpha1
kind: K8ssandraCluster
metadata:
  name: test
  namespace: k8ssandra-operator
spec:
  cassandra:
    datacenters:
    - config:
        jvmOptions:
          heapSize: 384Mi
      metadata:
        name: dc1
      size: 1
    serverVersion: 3.11.11
    cassandraTelemetry:
      prometheus:
        enabled: true
  stargate:
    size: 1
    telemetry:
      prometheus:
        enabled: true
```

after:

```yaml
apiVersion: k8ssandra.io/v1alpha1
kind: K8ssandraCluster
metadata:
  name: test
  namespace: k8ssandra-operator
spec:
  cassandra:
    datacenters:
    - config:
        jvmOptions:
          heapSize: 384Mi
      metadata:
        name: dc1
      size: 1
    serverVersion: 3.11.11
    telemetry:
      prometheus:
        enabled: true
  stargate:
    size: 1
    telemetry:
      prometheus:
        enabled: true
```

**Comment by Miles-Garnsey** [comment]
## Example of the problem I'm talking about

**Before**
```
apiVersion: k8ssandra.io/v1alpha1
kind: K8ssandraCluster
metadata:
  name: test
  namespace: k8ssandra-operator
spec:
  cassandra:
    datacenters:
    - config:
        jvmOptions:
          heapSize: 384Mi
      metadata:
        name: dc1
      size: 1
      cassandraTelemetry:
        prometheus:
          enabled: true
      stargate:
        telemetry: 
          prometheus:
            enabled: true
```

**After**

```
apiVersion: k8ssandra.io/v1alpha1
kind: K8ssandraCluster
metadata:
  name: test
  namespace: k8ssandra-operator
spec:
  cassandra:
    datacenters:
    - config:
        jvmOptions:
          heapSize: 384Mi
      metadata:
        name: dc1
      size: 1
      telemetry:
        prometheus:
          enabled: true
      stargate:
        telemetry: 
          prometheus:
            enabled: true
```

**Comment by jdonenine** [comment]
> I think it is clear from the parent/child relationships or nesting of properties that `cassandraTelemetry` or `telemetry` applies to Cassandra. Other than the `CassandraConfig` property, we don't prefix any of the other property names with `cassandra`.
> 
> @jdonenine thoughts?

So, yaml still sucks...

Say we look at it like this...

```
spec.cassandra.datacenters[0].telemetry.prometheus.enabled = true
```

and 

```
spec.cassandra.datacenters[0].stargate.telemetry.prometheus.enabled = true
```

I think in an ideal world, simply for consistency sake, I'd actually like to see `cassandra` represented as a level in the datacenter or `stargate` removed from it, like @Miles-Garnsey mentions.

In lieu of either of those things happening I don't think we need the special prefix, we don't prefix size with `cassandraSize` or whatever.

but we're talking semantics, I honestly don't really find either terribly abusive.

**Comment by jsanda** [comment]
Whether its declared at the cluster or at the dc-level, I think it's pretty clear. Consider the `size` property for comparison. We're not calling it `cassandraSize`. This is the same for all other properties at the DC level. Currently we have:

* serverImage
* size
* stopped
* serverVersion
* jmxInitContainerImage
* config
* resources
* racks
* networking
* storageConfig
* stargate
* mgmtAPIHeap
* cassandraTelemetry
* softPodAntiAffinity
* tolerations

In terms of naming `cassandraTelemetry` stands out as being less consistent with naming IMO.

**Comment by Miles-Garnsey** [comment]
Merge if you like @jsanda - but I will send every user who has a question on this topic in your direction... Until the end of time 😈

**Comment by jsanda** [comment]
>but I will send every user who has a question on this topic in your direction... Until the end of time

🤣 

Let's hold off and let others chime in if they are so inclined.

**Comment by adejanovski** [comment]
I'm +1 on just using `telemetry`.
It looks understandable to me that `cassandra.telemetry` is telemetry for Cassandra and `cassandra.stargate.telemetry` is telemetry for Stargate 🙂

**Comment by burmanm** [comment]
And I'm +1 using just `metrics` like everyone else in the industry..

**Pull request merged**
